[package]
edition = "2021"
name = "spin-analytics-macro"
version = "0.1.0"

[lib]
name = "spin_analytics_macro"
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "1.0", features = [ "full" ]}
